from betrobot.betting.proposers.bet_types_proposer_mixins.corners_proposer_mixins import CornersResults1ProposerMixin, CornersResults1XProposerMixin, CornersResultsX2ProposerMixin, CornersResults2ProposerMixin, CornersFirstPeriodResults1ProposerMixin, CornersFirstPeriodResults1XProposerMixin, CornersFirstPeriodResultsX2ProposerMixin, CornersFirstPeriodResults2ProposerMixin, CornersSecondPeriodResults1ProposerMixin, CornersSecondPeriodResults1XProposerMixin, CornersSecondPeriodResultsX2ProposerMixin, CornersSecondPeriodResults2ProposerMixin, CornersHandicapsHomeProposerMixin, CornersHandicapsAwayProposerMixin, CornersFirstPeriodHandicapsHomeProposerMixin, CornersFirstPeriodHandicapsAwayProposerMixin, CornersSecondPeriodHandicapsHomeProposerMixin, CornersSecondPeriodHandicapsAwayProposerMixin, CornersTotalsGreaterProposerMixin, CornersTotalsLesserProposerMixin, CornersFirstPeriodTotalsGreaterProposerMixin, CornersFirstPeriodTotalsLesserProposerMixin, CornersSecondPeriodTotalsGreaterProposerMixin, CornersSecondPeriodTotalsLesserProposerMixin, CornersIndividualTotalsHomeGreaterProposerMixin, CornersIndividualTotalsHomeLesserProposerMixin, CornersIndividualTotalsAwayGreaterProposerMixin, CornersIndividualTotalsAwayLesserProposerMixin, CornersFirstPeriodIndividualTotalsHomeGreaterProposerMixin, CornersFirstPeriodIndividualTotalsHomeLesserProposerMixin, CornersFirstPeriodIndividualTotalsAwayGreaterProposerMixin, CornersFirstPeriodIndividualTotalsAwayLesserProposerMixin, CornersSecondPeriodIndividualTotalsHomeGreaterProposerMixin, CornersSecondPeriodIndividualTotalsHomeLesserProposerMixin, CornersSecondPeriodIndividualTotalsAwayGreaterProposerMixin, CornersSecondPeriodIndividualTotalsAwayLesserProposerMixin

from betrobot.betting.proposers.probabilities_proposers.results_probabilities_proposers import Results1ProbabilityProposer, Results1XProbabilityProposer, ResultsX2ProbabilityProposer, Results2ProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.handicaps_probabilities_proposers import HandicapsHomeProbabilityProposer, HandicapsAwayProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.totals_probabilities_proposers import TotalsGreaterProbabilityProposer, TotalsLesserProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.individual_totals_probabilities_proposers import IndividualTotalsHomeGreaterProbabilityProposer, IndividualTotalsHomeLesserProbabilityProposer, IndividualTotalsAwayGreaterProbabilityProposer, IndividualTotalsAwayLesserProbabilityProposer


class CornersResults1ProbabilityProposer(CornersResults1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersResults1XProbabilityProposer(CornersResults1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersResultsX2ProbabilityProposer(CornersResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersResults2ProbabilityProposer(CornersResults2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersFirstPeriodResults1ProbabilityProposer(CornersFirstPeriodResults1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersFirstPeriodResults1XProbabilityProposer(CornersFirstPeriodResults1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersFirstPeriodResultsX2ProbabilityProposer(CornersFirstPeriodResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersFirstPeriodResults2ProbabilityProposer(CornersFirstPeriodResults2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersSecondPeriodResults1ProbabilityProposer(CornersSecondPeriodResults1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersSecondPeriodResults1XProbabilityProposer(CornersSecondPeriodResults1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersSecondPeriodResultsX2ProbabilityProposer(CornersSecondPeriodResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersSecondPeriodResults2ProbabilityProposer(CornersSecondPeriodResults2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersHandicapsHomeProbabilityProposer(CornersHandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersHandicapsAwayProbabilityProposer(CornersHandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsHomeProbabilityProposer(CornersFirstPeriodHandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsAwayProbabilityProposer(CornersFirstPeriodHandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsHomeProbabilityProposer(CornersSecondPeriodHandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsAwayProbabilityProposer(CornersSecondPeriodHandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersTotalsGreaterProbabilityProposer(CornersTotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersTotalsLesserProbabilityProposer(CornersTotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersFirstPeriodTotalsGreaterProbabilityProposer(CornersFirstPeriodTotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersFirstPeriodTotalsLesserProbabilityProposer(CornersFirstPeriodTotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersSecondPeriodTotalsGreaterProbabilityProposer(CornersSecondPeriodTotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersSecondPeriodTotalsLesserProbabilityProposer(CornersSecondPeriodTotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersIndividualTotalsHomeGreaterProbabilityProposer(CornersIndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsHomeLesserProbabilityProposer(CornersIndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersIndividualTotalsAwayGreaterProbabilityProposer(CornersIndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsAwayLesserProbabilityProposer(CornersIndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersFirstPeriodIndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersFirstPeriodIndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersFirstPeriodIndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersFirstPeriodIndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersSecondPeriodIndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersSecondPeriodIndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersSecondPeriodIndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersSecondPeriodIndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass
