from betrobot.betting.proposers.bet_types_proposer_mixins.corners_proposer_mixins import CornersResults1ProposerMixin, CornersResults1XProposerMixin, CornersResultsX2ProposerMixin, CornersResults2ProposerMixin, CornersFirstPeriodResults1ProposerMixin, CornersFirstPeriodResults1XProposerMixin, CornersFirstPeriodResultsX2ProposerMixin, CornersFirstPeriodResults2ProposerMixin, CornersSecondPeriodResults1ProposerMixin, CornersSecondPeriodResults1XProposerMixin, CornersSecondPeriodResultsX2ProposerMixin, CornersSecondPeriodResults2ProposerMixin, CornersHandicapsHomeProposerMixin, CornersHandicapsAwayProposerMixin, CornersFirstPeriodHandicapsHomeProposerMixin, CornersFirstPeriodHandicapsAwayProposerMixin, CornersSecondPeriodHandicapsHomeProposerMixin, CornersSecondPeriodHandicapsAwayProposerMixin, CornersTotalsGreaterProposerMixin

from betrobot.betting.proposers.diffs_diff_proposers.results_diffs_diff_proposers import Results1DiffsDiffProposer, Results1XDiffsDiffProposer, ResultsX2DiffsDiffProposer, Results2DiffsDiffProposer
from betrobot.betting.proposers.diffs_diff_proposers.handicaps_diffs_diff_proposers import HandicapsHomeDiffsDiffProposer, HandicapsAwayDiffsDiffProposer


class CornersResults1DiffsDiffProposer(CornersResults1ProposerMixin, Results1DiffsDiffProposer):
    pass


class CornersResults1XDiffsDiffProposer(CornersResults1XProposerMixin, Results1XDiffsDiffProposer):
    pass


class CornersResultsX2DiffsDiffProposer(CornersResultsX2ProposerMixin, ResultsX2DiffsDiffProposer):
    pass


class CornersResults2DiffsDiffProposer(CornersResults2ProposerMixin, Results2DiffsDiffProposer):
    pass


class CornersFirstPeriodResults1DiffsDiffProposer(CornersFirstPeriodResults1ProposerMixin, Results1DiffsDiffProposer):
    pass


class CornersFirstPeriodResults1XDiffsDiffProposer(CornersFirstPeriodResults1XProposerMixin, Results1XDiffsDiffProposer):
    pass


class CornersFirstPeriodResultsX2DiffsDiffProposer(CornersFirstPeriodResultsX2ProposerMixin, ResultsX2DiffsDiffProposer):
    pass


class CornersFirstPeriodResults2DiffsDiffProposer(CornersFirstPeriodResults2ProposerMixin, Results2DiffsDiffProposer):
    pass


class CornersSecondPeriodResults1DiffsDiffProposer(CornersSecondPeriodResults1ProposerMixin, Results1DiffsDiffProposer):
    pass


class CornersSecondPeriodResults1XDiffsDiffProposer(CornersSecondPeriodResults1XProposerMixin, Results1XDiffsDiffProposer):
    pass


class CornersSecondPeriodResultsX2DiffsDiffProposer(CornersSecondPeriodResultsX2ProposerMixin, ResultsX2DiffsDiffProposer):
    pass


class CornersSecondPeriodResults2DiffsDiffProposer(CornersSecondPeriodResults2ProposerMixin, Results2DiffsDiffProposer):
    pass


class CornersHandicapsHomeDiffsDiffProposer(CornersHandicapsHomeProposerMixin, HandicapsHomeDiffsDiffProposer):
    pass


class CornersHandicapsAwayDiffsDiffProposer(CornersHandicapsAwayProposerMixin, HandicapsAwayDiffsDiffProposer):
    pass


class CornersFirstPeriodHandicapsHomeDiffsDiffProposer(CornersFirstPeriodHandicapsHomeProposerMixin, HandicapsHomeDiffsDiffProposer):
    pass


class CornersFirstPeriodHandicapsAwayDiffsDiffProposer(CornersFirstPeriodHandicapsAwayProposerMixin, HandicapsAwayDiffsDiffProposer):
    pass


class CornersSecondPeriodHandicapsHomeDiffsDiffProposer(CornersSecondPeriodHandicapsHomeProposerMixin, HandicapsHomeDiffsDiffProposer):
    pass


class CornersSecondPeriodHandicapsAwayDiffsDiffProposer(CornersSecondPeriodHandicapsAwayProposerMixin, HandicapsAwayDiffsDiffProposer):
    pass
