from betrobot.betting.proposers.match_proposer_mixins import CornersMatchProposerMixin

from betrobot.betting.proposers.bets_proposer_mixins.results_proposer_mixins import Results1ProposerMixin, Results1XProposerMixin, ResultsX2ProposerMixin, Results2ProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_results_proposer_mixins import FirstPeriodResults1ProposerMixin, FirstPeriodResults1XProposerMixin, FirstPeriodResultsX2ProposerMixin, FirstPeriodResults2ProposerMixin, SecondPeriodResults1ProposerMixin, SecondPeriodResults1XProposerMixin, SecondPeriodResultsX2ProposerMixin, SecondPeriodResults2ProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.handicaps_proposer_mixins import HandicapsHomeProposerMixin, HandicapsAwayProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_handicaps_proposer_mixins import FirstPeriodHandicapsHomeProposerMixin, FirstPeriodHandicapsAwayProposerMixin, SecondPeriodHandicapsHomeProposerMixin, SecondPeriodHandicapsAwayProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.totals_proposer_mixins import TotalsGreaterProposerMixin, TotalsLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_totals_proposer_mixins import FirstPeriodTotalsGreaterProposerMixin, FirstPeriodTotalsLesserProposerMixin, SecondPeriodTotalsGreaterProposerMixin, SecondPeriodTotalsLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.individual_totals_proposer_mixins import IndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeLesserProposerMixin, IndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_individual_totals_proposer_mixins import FirstPeriodIndividualTotalsHomeGreaterProposerMixin, FirstPeriodIndividualTotalsHomeLesserProposerMixin, FirstPeriodIndividualTotalsAwayGreaterProposerMixin, FirstPeriodIndividualTotalsAwayLesserProposerMixin, SecondPeriodIndividualTotalsHomeGreaterProposerMixin, SecondPeriodIndividualTotalsHomeLesserProposerMixin, SecondPeriodIndividualTotalsAwayGreaterProposerMixin, SecondPeriodIndividualTotalsAwayLesserProposerMixin

from betrobot.betting.proposers.probability_proposers.results_probability_proposers import Results1ProbabilityProposer, Results1XProbabilityProposer, ResultsX2ProbabilityProposer, Results2ProbabilityProposer
from betrobot.betting.proposers.probability_proposers.period_results_probability_proposers import FirstPeriodResults1ProbabilityProposer, FirstPeriodResults1XProbabilityProposer, FirstPeriodResultsX2ProbabilityProposer, FirstPeriodResults2ProbabilityProposer, SecondPeriodResults1ProbabilityProposer, SecondPeriodResults1XProbabilityProposer, SecondPeriodResultsX2ProbabilityProposer, SecondPeriodResults2ProbabilityProposer
from betrobot.betting.proposers.probability_proposers.handicaps_probability_proposers import HandicapsHomeProbabilityProposer, HandicapsAwayProbabilityProposer
from betrobot.betting.proposers.probability_proposers.period_handicaps_probability_proposers import FirstPeriodHandicapsHomeProbabilityProposer, FirstPeriodHandicapsAwayProbabilityProposer, SecondPeriodHandicapsHomeProbabilityProposer, SecondPeriodHandicapsAwayProbabilityProposer
from betrobot.betting.proposers.probability_proposers.totals_probability_proposers import TotalsGreaterProbabilityProposer, TotalsLesserProbabilityProposer
from betrobot.betting.proposers.probability_proposers.period_totals_probability_proposers import FirstPeriodTotalsGreaterProbabilityProposer, FirstPeriodTotalsLesserProbabilityProposer, SecondPeriodTotalsGreaterProbabilityProposer, SecondPeriodTotalsLesserProbabilityProposer
from betrobot.betting.proposers.probability_proposers.individual_totals_probability_proposers import IndividualTotalsHomeGreaterProbabilityProposer, IndividualTotalsHomeLesserProbabilityProposer, IndividualTotalsAwayGreaterProbabilityProposer, IndividualTotalsAwayLesserProbabilityProposer
from betrobot.betting.proposers.probability_proposers.period_individual_totals_probability_proposers import FirstPeriodIndividualTotalsHomeGreaterProbabilityProposer, FirstPeriodIndividualTotalsHomeLesserProbabilityProposer, FirstPeriodIndividualTotalsAwayGreaterProbabilityProposer, FirstPeriodIndividualTotalsAwayLesserProbabilityProposer, SecondPeriodIndividualTotalsHomeGreaterProbabilityProposer, SecondPeriodIndividualTotalsHomeLesserProbabilityProposer, SecondPeriodIndividualTotalsAwayGreaterProbabilityProposer, SecondPeriodIndividualTotalsAwayLesserProbabilityProposer


class CornersResults1ProbabilityProposer(CornersMatchProposerMixin, Results1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersResults1XProbabilityProposer(CornersMatchProposerMixin, Results1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersResultsX2ProbabilityProposer(CornersMatchProposerMixin, ResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersResults2ProbabilityProposer(CornersMatchProposerMixin, Results2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersFirstPeriodResults1ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults1ProposerMixin, FirstPeriodResults1ProbabilityProposer):
    pass


class CornersFirstPeriodResults1XProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults1XProposerMixin, FirstPeriodResults1XProbabilityProposer):
    pass


class CornersFirstPeriodResultsX2ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResultsX2ProposerMixin, FirstPeriodResultsX2ProbabilityProposer):
    pass


class CornersFirstPeriodResults2ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults2ProposerMixin, FirstPeriodResults2ProbabilityProposer):
    pass


class CornersSecondPeriodResults1ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults1ProposerMixin, SecondPeriodResults1ProbabilityProposer):
    pass


class CornersSecondPeriodResults1XProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults1XProposerMixin, SecondPeriodResults1XProbabilityProposer):
    pass


class CornersSecondPeriodResultsX2ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResultsX2ProposerMixin, SecondPeriodResultsX2ProbabilityProposer):
    pass


class CornersSecondPeriodResults2ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults2ProposerMixin, SecondPeriodResults2ProbabilityProposer):
    pass


class CornersHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, HandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, HandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, FirstPeriodHandicapsHomeProposerMixin, FirstPeriodHandicapsHomeProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, FirstPeriodHandicapsAwayProposerMixin, FirstPeriodHandicapsAwayProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, SecondPeriodHandicapsHomeProposerMixin, SecondPeriodHandicapsHomeProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, SecondPeriodHandicapsAwayProposerMixin, SecondPeriodHandicapsAwayProbabilityProposer):
    pass


class CornersTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, TotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersTotalsLesserProbabilityProposer(CornersMatchProposerMixin, TotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersFirstPeriodTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodTotalsGreaterProposerMixin, FirstPeriodTotalsGreaterProbabilityProposer):
    pass


class CornersFirstPeriodTotalsLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodTotalsLesserProposerMixin, FirstPeriodTotalsLesserProbabilityProposer):
    pass


class CornersSecondPeriodTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodTotalsGreaterProposerMixin, SecondPeriodTotalsGreaterProbabilityProposer):
    pass


class CornersSecondPeriodTotalsLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodTotalsLesserProposerMixin, SecondPeriodTotalsLesserProbabilityProposer):
    pass


class CornersIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsHomeGreaterProposerMixin, FirstPeriodIndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsHomeLesserProposerMixin, FirstPeriodIndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsAwayGreaterProposerMixin, FirstPeriodIndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsAwayLesserProposerMixin, FirstPeriodIndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsHomeGreaterProposerMixin, SecondPeriodIndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsHomeLesserProposerMixin, SecondPeriodIndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsAwayGreaterProposerMixin, SecondPeriodIndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsAwayLesserProposerMixin, SecondPeriodIndividualTotalsAwayLesserProbabilityProposer):
    pass
