from betrobot.betting.proposers.match_proposer_mixins import CornersMatchProposerMixin

from betrobot.betting.proposers.bets_proposer_mixins.results_proposer_mixins import Results1ProposerMixin, Results1XProposerMixin, ResultsX2ProposerMixin, Results2ProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_results_proposer_mixins import FirstPeriodResults1ProposerMixin, FirstPeriodResults1XProposerMixin, FirstPeriodResultsX2ProposerMixin, FirstPeriodResults2ProposerMixin, SecondPeriodResults1ProposerMixin, SecondPeriodResults1XProposerMixin, SecondPeriodResultsX2ProposerMixin, SecondPeriodResults2ProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.handicaps_proposer_mixins import HandicapsHomeProposerMixin, HandicapsAwayProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_handicaps_proposer_mixins import FirstPeriodHandicapsHomeProposerMixin, FirstPeriodHandicapsAwayProposerMixin, SecondPeriodHandicapsHomeProposerMixin, SecondPeriodHandicapsAwayProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.totals_proposer_mixins import TotalsGreaterProposerMixin, TotalsLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_totals_proposer_mixins import FirstPeriodTotalsGreaterProposerMixin, FirstPeriodTotalsLesserProposerMixin, SecondPeriodTotalsGreaterProposerMixin, SecondPeriodTotalsLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.individual_totals_proposer_mixins import IndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeLesserProposerMixin, IndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayLesserProposerMixin
from betrobot.betting.proposers.bets_proposer_mixins.period_individual_totals_proposer_mixins import FirstPeriodIndividualTotalsHomeGreaterProposerMixin, FirstPeriodIndividualTotalsHomeLesserProposerMixin, FirstPeriodIndividualTotalsAwayGreaterProposerMixin, FirstPeriodIndividualTotalsAwayLesserProposerMixin, SecondPeriodIndividualTotalsHomeGreaterProposerMixin, SecondPeriodIndividualTotalsHomeLesserProposerMixin, SecondPeriodIndividualTotalsAwayGreaterProposerMixin, SecondPeriodIndividualTotalsAwayLesserProposerMixin

from betrobot.betting.proposers.probabilities_proposers.results_probabilities_proposers import Results1ProbabilityProposer, Results1XProbabilityProposer, ResultsX2ProbabilityProposer, Results2ProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.handicaps_probabilities_proposers import HandicapsHomeProbabilityProposer, HandicapsAwayProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.totals_probabilities_proposers import TotalsGreaterProbabilityProposer, TotalsLesserProbabilityProposer
from betrobot.betting.proposers.probabilities_proposers.individual_totals_probabilities_proposers import IndividualTotalsHomeGreaterProbabilityProposer, IndividualTotalsHomeLesserProbabilityProposer, IndividualTotalsAwayGreaterProbabilityProposer, IndividualTotalsAwayLesserProbabilityProposer


class CornersResults1ProbabilityProposer(CornersMatchProposerMixin, Results1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersResults1XProbabilityProposer(CornersMatchProposerMixin, Results1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersResultsX2ProbabilityProposer(CornersMatchProposerMixin, ResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersResults2ProbabilityProposer(CornersMatchProposerMixin, Results2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersFirstPeriodResults1ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersFirstPeriodResults1XProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersFirstPeriodResultsX2ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersFirstPeriodResults2ProbabilityProposer(CornersMatchProposerMixin, FirstPeriodResults2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersSecondPeriodResults1ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults1ProposerMixin, Results1ProbabilityProposer):
    pass


class CornersSecondPeriodResults1XProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults1XProposerMixin, Results1XProbabilityProposer):
    pass


class CornersSecondPeriodResultsX2ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResultsX2ProposerMixin, ResultsX2ProbabilityProposer):
    pass


class CornersSecondPeriodResults2ProbabilityProposer(CornersMatchProposerMixin, SecondPeriodResults2ProposerMixin, Results2ProbabilityProposer):
    pass


class CornersHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, HandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, HandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, FirstPeriodHandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersFirstPeriodHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, FirstPeriodHandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsHomeProbabilityProposer(CornersMatchProposerMixin, SecondPeriodHandicapsHomeProposerMixin, HandicapsHomeProbabilityProposer):
    pass


class CornersSecondPeriodHandicapsAwayProbabilityProposer(CornersMatchProposerMixin, SecondPeriodHandicapsAwayProposerMixin, HandicapsAwayProbabilityProposer):
    pass


class CornersTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, TotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersTotalsLesserProbabilityProposer(CornersMatchProposerMixin, TotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersFirstPeriodTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodTotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersFirstPeriodTotalsLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodTotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersSecondPeriodTotalsGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodTotalsGreaterProposerMixin, TotalsGreaterProbabilityProposer):
    pass


class CornersSecondPeriodTotalsLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodTotalsLesserProposerMixin, TotalsLesserProbabilityProposer):
    pass


class CornersIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, IndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersFirstPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, FirstPeriodIndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsHomeGreaterProposerMixin, IndividualTotalsHomeGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsHomeLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsHomeLesserProposerMixin, IndividualTotalsHomeLesserProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayGreaterProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsAwayGreaterProposerMixin, IndividualTotalsAwayGreaterProbabilityProposer):
    pass


class CornersSecondPeriodIndividualTotalsAwayLesserProbabilityProposer(CornersMatchProposerMixin, SecondPeriodIndividualTotalsAwayLesserProposerMixin, IndividualTotalsAwayLesserProbabilityProposer):
    pass
