from betrobot.betting.predictors.match_predictors import CornersMatchPredictor
from betrobot.betting.predictors.attack_defense_predictor import AttackDefensePredictor


class CornersResultProbabilitiesAttackDefensePredictor(CornersMatchPredictor, AttackDefensePredictor):
    pass
