from betrobot.betting.predictors.match_predictors import YellowCardsMatchPredictor
from betrobot.betting.predictors.attack_defense_predictor import AttackDefensePredictor


class YellowCardsResultProbabilitiesAttackDefensePredictor(YellowCardsMatchPredictor, AttackDefensePredictor):
    pass
